# Generated by Django 3.2.6 on 2021-09-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_author_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
    ]
